### ISSUE TITLE
Trup will delete messages which contain (reasonable) links with banned words

### ISSUE THREAD

**Issue by sophec** [unixporn/trup#63]
Example: someone's message was deleted for containing https://en.wikipedia.org/wiki/Retarded_potential

**Comment by aosync** [comment]
In my opinion, flagging messages with bad words is a bad solution. It conflicts with the purpose of the moderators, especially since several new ones are being hired.

**Comment by sophec** [comment]
@aosync this is not a conversation relevant to this issue, and it's one that has already been played out in the server itself.

**Comment by aosync** [comment]
I don't care.

**Comment by sophec** [comment]
If you think the mods should do things differently, you can take that up with us in the feedback channel on the server. However, this is not the place to discuss this, and there will be no further discussion on this topic here.

**Comment by aosync** [comment]
I am not un-okay with with stopping the conversation, you may stop worrying. I am just frustrated at you, repressing this in an unchill fashion. I believe that I should be able to believe that this conversation is relevant, and be corrected in a more harmless and smaller way. Yours to decide how to handle people though, now `:^)`.

To prevent any elevation of heat in further exchanges, I will cease sending messages in this issue after your response, if any.

**Comment by davidv171** [comment]
> Example: someone's message was deleted for containing https://en.wikipedia.org/wiki/Retarded_potential

What about non-links though? Discussing retarded potential without it being a link should not get deleted either. And I don't think anyone really wants to invest into some form of context-aware parsing. What I suggest is to not insta-delete the r word, but to define a separate list of words that get FLAGGED, not deleted. Meaning mods in #mods get a link to the message and they can check it out at their own pace. Unlike the other slurs on the list, this obviously has non-harmful uses.

**Comment by eepykate** [comment]
perhaps a better solution would be to have a whitelist or whatever, if a message matches a blocklist entry and also matches a whitelist entry it wouldn't get deleted, for example you could add 'retarded potential' to it and normally the r-word would get deleted, but when talking about that it wouldn't.

**Comment by davidv171** [comment]
@mlvzk The patch will allow people to just make up URLs to bypass the blocklist? If so, It should at least notify the mods.

**Comment by buffet** [comment]
Honestly, I'm not a big fan either.

It doesn't really fix the core issue. People will still not be able to talk about retarded potentials without sending the link, or referring to it as "it".

I think this is just one of those "unfixable" issues.

**Comment by mlvzk** [comment]
@davidv171 There are easier ways to bypass the filter if that's the user's intention, like putting a space in the middle of "[slur]". If someone does that it should be met with stronger consequences.

**Comment by sophec** [comment]
Honestly not sure why I ever opened this issue in the first place, I would say we shouldn't fix it tbh
